// <auto-generated />
using System;
using HVO.SkyMonitorV5.Data.Telemetry;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HVO.SkyMonitorV5.Data.Migrations.Telemetry
{
    [DbContext(typeof(SkyMonitorTelemetryContext))]
    [Migration("20251013051151_AddFrameExportAttempts")]
    partial class AddFrameExportAttempts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Telemetry.Entities.BackgroundStackerSampleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAtLocal")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at_local");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at_utc");

                    b.Property<double?>("FilterDurationMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("filter_duration_ms");

                    b.Property<int>("QueueCapacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("queue_capacity");

                    b.Property<int>("QueueDepth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("queue_depth");

                    b.Property<double>("QueueFillPercentage")
                        .HasColumnType("REAL")
                        .HasColumnName("queue_fill_percentage");

                    b.Property<double?>("QueueLatencyMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("queue_latency_ms");

                    b.Property<double>("QueueMemoryMegabytes")
                        .HasColumnType("REAL")
                        .HasColumnName("queue_memory_mb");

                    b.Property<int>("QueuePressureLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("queue_pressure_level");

                    b.Property<double?>("SecondsSinceLastCompleted")
                        .HasColumnType("REAL")
                        .HasColumnName("seconds_since_last_completed");

                    b.Property<double?>("StackDurationMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("stack_duration_ms");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtLocal")
                        .HasDatabaseName("ix_background_stacker_sample_local");

                    b.ToTable("background_stacker_sample", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Telemetry.Entities.CapturePacingSampleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AdjustedDelayMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("adjusted_delay_ms");

                    b.Property<int>("BaseDelayMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_delay_ms");

                    b.Property<DateTimeOffset>("CapturedAtLocal")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at_local");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at_utc");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<bool>("PenaltyActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("penalty_active");

                    b.Property<int>("PenaltyAdditionalDelayMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("penalty_delay_ms");

                    b.Property<DateTimeOffset?>("PenaltyExpiresAtLocal")
                        .HasColumnType("TEXT")
                        .HasColumnName("penalty_expires_at_local");

                    b.Property<int>("PressureAdditionalDelayMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pressure_delay_ms");

                    b.Property<int>("QueuePressureLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("queue_pressure_level");

                    b.Property<bool>("UsingBackgroundStacker")
                        .HasColumnType("INTEGER")
                        .HasColumnName("using_background_stacker");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtLocal")
                        .HasDatabaseName("ix_capture_pacing_sample_local");

                    b.ToTable("capture_pacing_sample", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Telemetry.Entities.FilterMetricSampleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("AppliedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("applied_count");

                    b.Property<double?>("AverageDurationMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("average_duration_ms");

                    b.Property<DateTimeOffset>("CapturedAtLocal")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at_local");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("FilterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("filter_name");

                    b.Property<double?>("LastDurationMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("last_duration_ms");

                    b.HasKey("Id");

                    b.HasIndex("FilterName", "CapturedAtLocal")
                        .HasDatabaseName("ix_filter_metric_sample_filter_time");

                    b.ToTable("filter_metric_sample", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Telemetry.Entities.FrameExportAttemptEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAtLocal")
                        .HasColumnType("TEXT")
                        .HasColumnName("attempted_at_local");

                    b.Property<DateTimeOffset>("AttemptedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("attempted_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<Guid>("FrameId")
                        .HasColumnType("TEXT")
                        .HasColumnName("frame_id");

                    b.Property<int?>("FramesStacked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frames_stacked");

                    b.Property<int?>("IntegrationMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("integration_ms");

                    b.Property<double?>("LatencyMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("latency_ms");

                    b.Property<long?>("PayloadBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payload_bytes");

                    b.Property<string>("PayloadContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_content_type");

                    b.Property<string>("PayloadExtension")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_extension");

                    b.Property<double?>("ProcessingMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("processing_ms");

                    b.Property<double?>("QueueLatencyMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("queue_latency_ms");

                    b.Property<string>("SinkName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("sink_name");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stage");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAtLocal")
                        .HasDatabaseName("ix_frame_export_attempt_local");

                    b.HasIndex("FrameId")
                        .HasDatabaseName("ix_frame_export_attempt_frame");

                    b.HasIndex("Stage", "SinkName")
                        .HasDatabaseName("ix_frame_export_attempt_stage_sink");

                    b.ToTable("frame_export_attempt", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Telemetry.Entities.ProcessingQueueSampleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("AverageEnqueueWaitMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("avg_enqueue_wait_ms");

                    b.Property<double>("AverageProcessingMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("avg_processing_ms");

                    b.Property<int>("BackpressureEvents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("backpressure_events");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CapturedAtLocal")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at_local");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at_utc");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("depth");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<double>("LastEnqueueWaitMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("last_enqueue_wait_ms");

                    b.Property<double>("LastProcessingMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("last_processing_ms");

                    b.Property<double>("PeakEnqueueWaitMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("peak_enqueue_wait_ms");

                    b.Property<double>("PeakProcessingMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("peak_processing_ms");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtLocal")
                        .HasDatabaseName("ix_processing_queue_sample_local");

                    b.ToTable("processing_queue_sample", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Telemetry.Entities.RemoteDispatchAttemptEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAtLocal")
                        .HasColumnType("TEXT")
                        .HasColumnName("attempted_at_local");

                    b.Property<DateTimeOffset>("AttemptedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("attempted_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("FormatKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("format_key");

                    b.Property<double?>("LatencyMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Message")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER")
                        .HasColumnName("outcome");

                    b.Property<long?>("PayloadBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("payload_bytes");

                    b.Property<string>("PayloadContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_content_type");

                    b.Property<string>("PayloadExtension")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_extension");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAtLocal")
                        .HasDatabaseName("ix_remote_dispatch_attempt_local");

                    b.HasIndex("FormatKey")
                        .HasDatabaseName("ix_remote_dispatch_attempt_format");

                    b.HasIndex("Outcome")
                        .HasDatabaseName("ix_remote_dispatch_attempt_outcome");

                    b.ToTable("remote_dispatch_attempt", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Telemetry.Entities.TelemetryEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Detail")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtLocal")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_local");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("properties_json");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<string>("Summary")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_telemetry_event_category");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_telemetry_event_type");

                    b.HasIndex("OccurredAtLocal")
                        .HasDatabaseName("ix_telemetry_event_local");

                    b.ToTable("telemetry_event", (string)null);
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Telemetry.Entities.TelemetrySystemProfileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalPropertiesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("additional_properties_json");

                    b.Property<string>("CpuModel")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("cpu_model");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_seen_at_utc");

                    b.Property<string>("FrameworkDescription")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("framework_description");

                    b.Property<string>("HardwareModel")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("hardware_model");

                    b.Property<string>("HostName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("host_name");

                    b.Property<bool?>("IsContainerized")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_containerized");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("MachineName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_name");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("operating_system");

                    b.Property<string>("OsArchitecture")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("os_architecture");

                    b.Property<string>("ProcessArchitecture")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("process_architecture");

                    b.Property<int?>("ProcessorCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("processor_count");

                    b.Property<string>("SystemHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("system_hash");

                    b.Property<double?>("TotalMemoryMegabytes")
                        .HasColumnType("REAL")
                        .HasColumnName("total_memory_mb");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAtUtc")
                        .HasDatabaseName("ix_telemetry_system_profile_last_seen");

                    b.HasIndex("SystemHash")
                        .IsUnique()
                        .HasDatabaseName("ux_telemetry_system_profile_hash");

                    b.ToTable("telemetry_system_profile", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
