// <auto-generated />
using System;
using HVO.SkyMonitorV5.Data.Archive;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HVO.SkyMonitorV5.Data.Migrations.ImageFrameArchive
{
    [DbContext(typeof(ImageFrameArchiveContext))]
    [Migration("20251021201550_InitialImageFrameArchive")]
    partial class InitialImageFrameArchive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Archive.Entities.FrameArchiveEntity", b =>
                {
                    b.Property<Guid>("FrameId")
                        .HasColumnType("TEXT")
                        .HasColumnName("frame_id");

                    b.Property<string>("AppliedFilters")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("applied_filters_json");

                    b.Property<DateTimeOffset>("ArchivedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("camera_name");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at_utc");

                    b.Property<int>("FramesStacked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frames_stacked");

                    b.Property<double?>("FullPipelineMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("full_pipeline_ms");

                    b.Property<int?>("IntegrationMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("integration_ms");

                    b.Property<string>("MediaBucket")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_bucket");

                    b.Property<string>("MediaFilePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_file_path");

                    b.Property<string>("MediaObjectKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_object_key");

                    b.Property<string>("PayloadContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_content_type");

                    b.Property<string>("PayloadExtension")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_extension");

                    b.Property<double?>("ProcessingMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("processing_ms");

                    b.Property<double?>("QueueLatencyMilliseconds")
                        .HasColumnType("REAL")
                        .HasColumnName("queue_latency_ms");

                    b.Property<string>("RawMediaBucket")
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_media_bucket");

                    b.Property<string>("RawMediaFilePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_media_file_path");

                    b.Property<string>("RawMediaObjectKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_media_object_key");

                    b.Property<string>("RigName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rig_name");

                    b.Property<string>("ThumbnailBucket")
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbnail_bucket");

                    b.Property<string>("ThumbnailFilePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbnail_file_path");

                    b.Property<string>("ThumbnailObjectKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("thumbnail_object_key");

                    b.HasKey("FrameId");

                    b.HasIndex("CameraName")
                        .HasDatabaseName("ix_image_frame_archive_camera_name");

                    b.HasIndex("CapturedAtUtc")
                        .HasDatabaseName("ix_image_frame_archive_captured_at");

                    b.HasIndex("FramesStacked")
                        .HasDatabaseName("ix_image_frame_archive_frames_stacked");

                    b.HasIndex("RigName")
                        .HasDatabaseName("ix_image_frame_archive_rig_name");

                    b.ToTable("image_frame_archive", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
