namespace HVO.ZWOOptical.ASISDK
{
public static partial class ASICamera2
{
        public enum ASI_ERROR_CODE
    { //ASI ERROR CODE
        ASI_SUCCESS = 0,
        ASI_ERROR_INVALID_INDEX,
        ASI_ERROR_INVALID_ID,
        ASI_ERROR_INVALID_CONTROL_TYPE,
        ASI_ERROR_CAMERA_CLOSED,
        ASI_ERROR_CAMERA_REMOVED,
        ASI_ERROR_INVALID_PATH,
        ASI_ERROR_INVALID_FILEFORMAT,
        ASI_ERROR_INVALID_SIZE,
        ASI_ERROR_INVALID_IMGTYPE,
        ASI_ERROR_OUTOF_BOUNDARY,
        ASI_ERROR_TIMEOUT,
        ASI_ERROR_INVALID_SEQUENCE,
        ASI_ERROR_BUFFER_TOO_SMALL,
        ASI_ERROR_VIDEO_MODE_ACTIVE,
        ASI_ERROR_EXPOSURE_IN_PROGRESS,
        ASI_ERROR_GENERAL_ERROR,
        ASI_ERROR_INVALID_MODE,
        ASI_ERROR_GPS_NOT_SUPPORTED,
        ASI_ERROR_GPS_VER_ERR,
        ASI_ERROR_GPS_FPGA_ERR,
        ASI_ERROR_GPS_PARAM_OUT_OF_RANGE,
        ASI_ERROR_GPS_DATA_INVALID,
        ASI_ERROR_END
    };


}
}
