services:
  website-v9:
    build:
      context: ../..
      dockerfile: src/HVO.WebSite/HVO.WebSite.v9/Dockerfile
    image: hvo/website-v9:dev
    container_name: hvo-website-v9
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5202:8080"
    networks:
      - hvo-network

  website-playground:
    profiles: [ "playground" ]
    build:
      context: ../..
      dockerfile: src/HVO.WebSite/HVO.WebSite.Playground/Dockerfile
    image: hvo/website-playground:dev
    container_name: hvo-website-playground
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5203:8080"
    networks:
      - hvo-network

networks:
  hvo-network:
    name: hvo-network
    driver: bridge
