// <auto-generated />
using HVO.SkyMonitorV5.Data.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HVO.SkyMonitorV5.Data.Migrations.Configuration
{
    [DbContext(typeof(SkyMonitorConfigurationContext))]
    [Migration("20251014003816_AddCameraPipelineBounds")]
    partial class AddCameraPipelineBounds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Configurations.Entities.CameraAdapterConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AdapterType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("adapter_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("RigId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rig_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RigId");

                    b.ToTable("camera_adapter_config", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdapterType = "Mock",
                            Name = "MockFisheye",
                            RigId = 1
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Configurations.Entities.CameraCatalogCameraEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AdapterName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("adapter_name");

                    b.Property<string>("AdditionalTagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("additional_tags_json");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body_type");

                    b.Property<string>("ColorMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("color_mode");

                    b.Property<string>("Cooling")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cooling");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("driver_id");

                    b.Property<string>("DriverVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("driver_version");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_synthetic");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<double>("PixelSizeMicrons")
                        .HasColumnType("REAL")
                        .HasColumnName("pixel_size_microns");

                    b.Property<double?>("SensorCxPixels")
                        .HasColumnType("REAL")
                        .HasColumnName("sensor_cx_px");

                    b.Property<double?>("SensorCyPixels")
                        .HasColumnType("REAL")
                        .HasColumnName("sensor_cy_px");

                    b.Property<int>("SensorHeightPixels")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sensor_height_px");

                    b.Property<string>("SensorTechnology")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sensor_technology");

                    b.Property<int>("SensorWidthPixels")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sensor_width_px");

                    b.Property<bool>("SupportsExposureControl")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supports_exposure_control");

                    b.Property<bool>("SupportsGainControl")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supports_gain_control");

                    b.Property<bool>("SupportsSoftwareBinning")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supports_software_binning");

                    b.Property<bool>("SupportsTemperatureTelemetry")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supports_temperature_telemetry");

                    b.Property<string>("SyntheticProfile")
                        .HasColumnType("TEXT")
                        .HasColumnName("synthetic_profile");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("camera_catalog_camera", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdapterName = "MockCameraAdapter",
                            AdditionalTagsJson = "[\"Simulation\"]",
                            BodyType = "Synthetic",
                            ColorMode = "Monochrome",
                            Cooling = "None",
                            DisplayName = "Mock ASI174MM",
                            DriverId = "Synthetic",
                            DriverVersion = "2.0.0",
                            IsSynthetic = true,
                            Key = "MockASI174MM",
                            Manufacturer = "HVO",
                            Model = "Mock Fisheye AllSky",
                            PixelSizeMicrons = 5.8600000000000003,
                            SensorHeightPixels = 1216,
                            SensorTechnology = "Cmos",
                            SensorWidthPixels = 1936,
                            SupportsExposureControl = true,
                            SupportsGainControl = true,
                            SupportsSoftwareBinning = true,
                            SupportsTemperatureTelemetry = false,
                            SyntheticProfile = "MockFisheye"
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Configurations.Entities.CameraCatalogLensEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<double>("FieldOfViewXDegrees")
                        .HasColumnType("REAL")
                        .HasColumnName("fov_x_deg");

                    b.Property<double?>("FieldOfViewYDegrees")
                        .HasColumnType("REAL")
                        .HasColumnName("fov_y_deg");

                    b.Property<double>("FocalLengthMillimeters")
                        .HasColumnType("REAL")
                        .HasColumnName("focal_length_mm");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("ProjectionModel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("projection_model");

                    b.Property<double>("RollDegrees")
                        .HasColumnType("REAL")
                        .HasColumnName("roll_deg");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("camera_catalog_lens", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Fujinon FE185C086HA-1",
                            FieldOfViewXDegrees = 185.0,
                            FieldOfViewYDegrees = 185.0,
                            FocalLengthMillimeters = 2.7000000000000002,
                            Key = "Fujinon_FE185C086HA_1",
                            Kind = "Fisheye",
                            ProjectionModel = "Equidistant",
                            RollDegrees = 0.0
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Configurations.Entities.CameraPipelineConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CaptureIntervalMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capture_interval_ms");

                    b.Property<int>("DayExposureMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_exposure_ms");

                    b.Property<int>("DayGain")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_gain");

                    b.Property<int>("DayMaximumExposureMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_max_exposure_ms");

                    b.Property<int>("DayMaximumGain")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_max_gain");

                    b.Property<int>("DayMinimumExposureMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_min_exposure_ms");

                    b.Property<int>("DayMinimumGain")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_min_gain");

                    b.Property<int>("DayNightTransitionHourOffset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_night_transition_hour_offset");

                    b.Property<int>("DayStartExposureMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_start_exposure_ms");

                    b.Property<int>("DayStartGain")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_start_gain");

                    b.Property<bool>("EnableImageOverlays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable_image_overlays");

                    b.Property<bool>("EnableStacking")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable_stacking");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("NightExposureMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("night_exposure_ms");

                    b.Property<int>("NightGain")
                        .HasColumnType("INTEGER")
                        .HasColumnName("night_gain");

                    b.Property<int>("NightMaximumExposureMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("night_max_exposure_ms");

                    b.Property<int>("NightMaximumGain")
                        .HasColumnType("INTEGER")
                        .HasColumnName("night_max_gain");

                    b.Property<int>("NightMinimumExposureMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("night_min_exposure_ms");

                    b.Property<int>("NightMinimumGain")
                        .HasColumnType("INTEGER")
                        .HasColumnName("night_min_gain");

                    b.Property<int>("NightStartExposureMilliseconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("night_start_exposure_ms");

                    b.Property<int>("NightStartGain")
                        .HasColumnType("INTEGER")
                        .HasColumnName("night_start_gain");

                    b.Property<string>("OverlayTextFormat")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("overlay_text_format");

                    b.Property<int>("StackingBufferIntegrationSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stacking_buffer_integration_seconds");

                    b.Property<int>("StackingBufferMinimumFrames")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stacking_buffer_min_frames");

                    b.Property<int>("StackingFrameCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stacking_frame_count");

                    b.HasKey("Id");

                    b.ToTable("camera_pipeline_config", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaptureIntervalMilliseconds = 1000,
                            DayExposureMilliseconds = 50,
                            DayGain = 50,
                            DayMaximumExposureMilliseconds = 60000,
                            DayMaximumGain = 500,
                            DayMinimumExposureMilliseconds = 1,
                            DayMinimumGain = 0,
                            DayNightTransitionHourOffset = 0,
                            DayStartExposureMilliseconds = 2000,
                            DayStartGain = 50,
                            EnableImageOverlays = true,
                            EnableStacking = true,
                            Name = "Default",
                            NightExposureMilliseconds = 5000,
                            NightGain = 200,
                            NightMaximumExposureMilliseconds = 60000,
                            NightMaximumGain = 500,
                            NightMinimumExposureMilliseconds = 1,
                            NightMinimumGain = 0,
                            NightStartExposureMilliseconds = 5000,
                            NightStartGain = 200,
                            OverlayTextFormat = "yyyy-MM-dd HH:mm:ss zzz",
                            StackingBufferIntegrationSeconds = 120,
                            StackingBufferMinimumFrames = 24,
                            StackingFrameCount = 4
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Configurations.Entities.ObservatorySiteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("LatitudeDegrees")
                        .HasColumnType("REAL")
                        .HasColumnName("latitude_degrees");

                    b.Property<double>("LongitudeDegrees")
                        .HasColumnType("REAL")
                        .HasColumnName("longitude_degrees");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("observatory_site", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LatitudeDegrees = 35.347000000000001,
                            LongitudeDegrees = -113.878,
                            Name = "Hualapai Valley Observatory",
                            Slug = "hvo-primary",
                            TimeZoneId = "America/Phoenix"
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Configurations.Entities.RigCatalogEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("BoresightAltitudeDegrees")
                        .HasColumnType("REAL")
                        .HasColumnName("boresight_alt_deg");

                    b.Property<double>("BoresightAzimuthDegrees")
                        .HasColumnType("REAL")
                        .HasColumnName("boresight_az_deg");

                    b.Property<int>("CameraId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("camera_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<int>("LensId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lens_id");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("LensId");

                    b.ToTable("rig_catalog_entry", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoresightAltitudeDegrees = 90.0,
                            BoresightAzimuthDegrees = 0.0,
                            CameraId = 1,
                            DisplayName = "Mock Fisheye",
                            IsActive = true,
                            Key = "MockFisheye",
                            LensId = 1
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Configurations.Entities.StarCatalogSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DeclinationBands")
                        .HasColumnType("INTEGER")
                        .HasColumnName("declination_bands");

                    b.Property<bool>("IncludeMoon")
                        .HasColumnType("INTEGER")
                        .HasColumnName("include_moon");

                    b.Property<bool>("IncludeOuterPlanets")
                        .HasColumnType("INTEGER")
                        .HasColumnName("include_outer_planets");

                    b.Property<bool>("IncludePlanets")
                        .HasColumnType("INTEGER")
                        .HasColumnName("include_planets");

                    b.Property<bool>("IncludeSun")
                        .HasColumnType("INTEGER")
                        .HasColumnName("include_sun");

                    b.Property<double>("MagnitudeLimit")
                        .HasColumnType("REAL")
                        .HasColumnName("magnitude_limit");

                    b.Property<double>("MinMaxAltitudeDegrees")
                        .HasColumnType("REAL")
                        .HasColumnName("min_max_altitude_degrees");

                    b.Property<int>("RightAscensionBins")
                        .HasColumnType("INTEGER")
                        .HasColumnName("right_ascension_bins");

                    b.Property<bool>("StratifiedSelection")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stratified_selection");

                    b.Property<int>("TopStarCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("top_star_count");

                    b.HasKey("Id");

                    b.ToTable("star_catalog_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeclinationBands = 8,
                            IncludeMoon = true,
                            IncludeOuterPlanets = true,
                            IncludePlanets = true,
                            IncludeSun = false,
                            MagnitudeLimit = 6.5,
                            MinMaxAltitudeDegrees = 10.0,
                            RightAscensionBins = 24,
                            StratifiedSelection = false,
                            TopStarCount = 500
                        });
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Configurations.Entities.CameraAdapterConfigEntity", b =>
                {
                    b.HasOne("HVO.SkyMonitorV5.Data.Configurations.Entities.RigCatalogEntryEntity", "Rig")
                        .WithMany()
                        .HasForeignKey("RigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rig");
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Configurations.Entities.CameraPipelineConfigEntity", b =>
                {
                    b.OwnsOne("HVO.SkyMonitorV5.Data.Configurations.Entities.BackgroundStackerSettings", "BackgroundStacker", b1 =>
                        {
                            b1.Property<int>("CameraPipelineConfigEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CompressionMode")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("bg_compression_mode");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("bg_enabled");

                            b1.Property<string>("OverflowPolicy")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("bg_overflow_policy");

                            b1.Property<int>("QueueCapacity")
                                .HasColumnType("INTEGER")
                                .HasColumnName("bg_queue_capacity");

                            b1.Property<int>("RestartDelaySeconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("bg_restart_delay_seconds");

                            b1.HasKey("CameraPipelineConfigEntityId");

                            b1.ToTable("camera_pipeline_config");

                            b1.WithOwner()
                                .HasForeignKey("CameraPipelineConfigEntityId");

                            b1.OwnsOne("HVO.SkyMonitorV5.Data.Configurations.Entities.AdaptiveBackgroundQueueSettings", "AdaptiveQueue", b2 =>
                                {
                                    b2.Property<int>("BackgroundStackerSettingsCameraPipelineConfigEntityId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("CooldownSeconds")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("bg_adaptive_cooldown_seconds");

                                    b2.Property<int>("DecreaseStep")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("bg_adaptive_decrease_step");

                                    b2.Property<bool>("Enabled")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("bg_adaptive_enabled");

                                    b2.Property<int>("EvaluationWindowSeconds")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("bg_adaptive_evaluation_window_seconds");

                                    b2.Property<int>("IncreaseStep")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("bg_adaptive_increase_step");

                                    b2.Property<int>("MaxCapacity")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("bg_adaptive_max_capacity");

                                    b2.Property<int>("MinCapacity")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("bg_adaptive_min_capacity");

                                    b2.Property<int>("ScaleDownThresholdPercent")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("bg_adaptive_scale_down_percent");

                                    b2.Property<int>("ScaleUpThresholdPercent")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("bg_adaptive_scale_up_percent");

                                    b2.HasKey("BackgroundStackerSettingsCameraPipelineConfigEntityId");

                                    b2.ToTable("camera_pipeline_config");

                                    b2.WithOwner()
                                        .HasForeignKey("BackgroundStackerSettingsCameraPipelineConfigEntityId");

                                    b2.HasData(
                                        new
                                        {
                                            BackgroundStackerSettingsCameraPipelineConfigEntityId = 1,
                                            CooldownSeconds = 30,
                                            DecreaseStep = 4,
                                            Enabled = true,
                                            EvaluationWindowSeconds = 6,
                                            IncreaseStep = 4,
                                            MaxCapacity = 48,
                                            MinCapacity = 24,
                                            ScaleDownThresholdPercent = 35,
                                            ScaleUpThresholdPercent = 75
                                        });
                                });

                            b1.Navigation("AdaptiveQueue")
                                .IsRequired();

                            b1.HasData(
                                new
                                {
                                    CameraPipelineConfigEntityId = 1,
                                    CompressionMode = "None",
                                    Enabled = true,
                                    OverflowPolicy = "Block",
                                    QueueCapacity = 32,
                                    RestartDelaySeconds = 5
                                });
                        });

                    b.OwnsOne("HVO.SkyMonitorV5.Data.Configurations.Entities.CapturePacingSettings", "CapturePacing", b1 =>
                        {
                            b1.Property<int>("CameraPipelineConfigEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CriticalAdditionalDelayMilliseconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("pacing_critical_delay_ms");

                            b1.Property<int>("ElevatedAdditionalDelayMilliseconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("pacing_elevated_delay_ms");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("pacing_enabled");

                            b1.Property<int>("HighAdditionalDelayMilliseconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("pacing_high_delay_ms");

                            b1.Property<int>("MaxDelayMilliseconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("pacing_max_delay_ms");

                            b1.Property<int>("RampDownStepMilliseconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("pacing_ramp_down_step_ms");

                            b1.Property<int>("RampUpStepMilliseconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("pacing_ramp_up_step_ms");

                            b1.Property<int>("RejectionPenaltyDurationSeconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("pacing_rejection_penalty_duration_seconds");

                            b1.Property<int>("RejectionPenaltyMilliseconds")
                                .HasColumnType("INTEGER")
                                .HasColumnName("pacing_rejection_penalty_ms");

                            b1.HasKey("CameraPipelineConfigEntityId");

                            b1.ToTable("camera_pipeline_config");

                            b1.WithOwner()
                                .HasForeignKey("CameraPipelineConfigEntityId");

                            b1.HasData(
                                new
                                {
                                    CameraPipelineConfigEntityId = 1,
                                    CriticalAdditionalDelayMilliseconds = 1000,
                                    ElevatedAdditionalDelayMilliseconds = 250,
                                    Enabled = true,
                                    HighAdditionalDelayMilliseconds = 500,
                                    MaxDelayMilliseconds = 6000,
                                    RampDownStepMilliseconds = 300,
                                    RampUpStepMilliseconds = 150,
                                    RejectionPenaltyDurationSeconds = 12,
                                    RejectionPenaltyMilliseconds = 2000
                                });
                        });

                    b.OwnsOne("HVO.SkyMonitorV5.Data.Configurations.Entities.CardinalDirectionsOverlaySettings", "CardinalDirections", b1 =>
                        {
                            b1.Property<int>("CameraPipelineConfigEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CircleColor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("cardinal_circle_color");

                            b1.Property<string>("CircleLineStyle")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("cardinal_circle_line_style");

                            b1.Property<int>("CircleOpacity")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cardinal_circle_opacity");

                            b1.Property<int>("CircleThickness")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cardinal_circle_thickness");

                            b1.Property<int>("LabelCornerRadius")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cardinal_label_corner_radius");

                            b1.Property<string>("LabelEast")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("cardinal_label_east");

                            b1.Property<int>("LabelFillOpacity")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cardinal_label_fill_opacity");

                            b1.Property<int>("LabelFontSize")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cardinal_label_font_size");

                            b1.Property<string>("LabelNorth")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("cardinal_label_north");

                            b1.Property<int>("LabelPadding")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cardinal_label_padding");

                            b1.Property<string>("LabelSouth")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("cardinal_label_south");

                            b1.Property<string>("LabelWest")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("cardinal_label_west");

                            b1.Property<int>("OffsetXPixels")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cardinal_offset_x");

                            b1.Property<int>("OffsetYPixels")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cardinal_offset_y");

                            b1.Property<int>("RadiusOffsetPixels")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cardinal_radius_offset_px");

                            b1.Property<int>("RotationDegrees")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cardinal_rotation_deg");

                            b1.Property<bool>("SwapEastWest")
                                .HasColumnType("INTEGER")
                                .HasColumnName("cardinal_swap_east_west");

                            b1.HasKey("CameraPipelineConfigEntityId");

                            b1.ToTable("camera_pipeline_config");

                            b1.WithOwner()
                                .HasForeignKey("CameraPipelineConfigEntityId");

                            b1.HasData(
                                new
                                {
                                    CameraPipelineConfigEntityId = 1,
                                    CircleColor = "#C8D2E6",
                                    CircleLineStyle = "LongDash",
                                    CircleOpacity = 170,
                                    CircleThickness = 1,
                                    LabelCornerRadius = 6,
                                    LabelEast = "E",
                                    LabelFillOpacity = 220,
                                    LabelFontSize = 18,
                                    LabelNorth = "N",
                                    LabelPadding = 6,
                                    LabelSouth = "S",
                                    LabelWest = "W",
                                    OffsetXPixels = 0,
                                    OffsetYPixels = 0,
                                    RadiusOffsetPixels = -35,
                                    RotationDegrees = 0,
                                    SwapEastWest = true
                                });
                        });

                    b.OwnsOne("HVO.SkyMonitorV5.Data.Configurations.Entities.CelestialAnnotationSettings", "CelestialAnnotations", b1 =>
                        {
                            b1.Property<int>("CameraPipelineConfigEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("AnnotatePlanets")
                                .HasColumnType("INTEGER")
                                .HasColumnName("celestial_annotate_planets");

                            b1.Property<int>("AutoStarCount")
                                .HasColumnType("INTEGER")
                                .HasColumnName("celestial_auto_star_count");

                            b1.Property<double>("AutoStarMagnitudeLimit")
                                .HasColumnType("REAL")
                                .HasColumnName("celestial_auto_star_magnitude_limit");

                            b1.Property<string>("DeepSkyLabelColor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("celestial_deep_sky_label_color");

                            b1.Property<double>("DeepSkyRingRadius")
                                .HasColumnType("REAL")
                                .HasColumnName("celestial_deep_sky_ring_radius");

                            b1.Property<double>("LabelFontSize")
                                .HasColumnType("REAL")
                                .HasColumnName("celestial_label_font_size");

                            b1.Property<string>("PlanetLabelColor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("celestial_planet_label_color");

                            b1.Property<double>("PlanetRingRadius")
                                .HasColumnType("REAL")
                                .HasColumnName("celestial_planet_ring_radius");

                            b1.Property<string>("StarLabelColor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("celestial_star_label_color");

                            b1.Property<double>("StarRingRadius")
                                .HasColumnType("REAL")
                                .HasColumnName("celestial_star_ring_radius");

                            b1.Property<bool>("UseAutomaticStarSelection")
                                .HasColumnType("INTEGER")
                                .HasColumnName("celestial_use_auto_star_selection");

                            b1.HasKey("CameraPipelineConfigEntityId");

                            b1.ToTable("camera_pipeline_config");

                            b1.WithOwner()
                                .HasForeignKey("CameraPipelineConfigEntityId");

                            b1.OwnsMany("HVO.SkyMonitorV5.Data.Configurations.Entities.CelestialAnnotationDeepSkyObjectEntity", "DeepSkyObjects", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("id");

                                    b2.Property<string>("Color")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("color");

                                    b2.Property<double>("DeclinationDegrees")
                                        .HasColumnType("REAL")
                                        .HasColumnName("declination_degrees");

                                    b2.Property<double>("Magnitude")
                                        .HasColumnType("REAL")
                                        .HasColumnName("magnitude");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("name");

                                    b2.Property<double>("RightAscensionHours")
                                        .HasColumnType("REAL")
                                        .HasColumnName("right_ascension_hours");

                                    b2.Property<int>("pipeline_id")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("pipeline_id");

                                    b2.HasKey("Id");

                                    b2.HasIndex("pipeline_id");

                                    b2.ToTable("celestial_annotation_deep_sky_object", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("pipeline_id");

                                    b2.HasData(
                                        new
                                        {
                                            Id = 1,
                                            Color = "#8FB7FF",
                                            DeclinationDegrees = 41.268999999999998,
                                            Magnitude = 3.3999999999999999,
                                            Name = "M31 (Andromeda Galaxy)",
                                            RightAscensionHours = 0.71199999999999997,
                                            pipeline_id = 1
                                        },
                                        new
                                        {
                                            Id = 2,
                                            Color = "#C6A7FF",
                                            DeclinationDegrees = 36.466999999999999,
                                            Magnitude = 5.7999999999999998,
                                            Name = "M13 (Great Globular Cluster)",
                                            RightAscensionHours = 16.695,
                                            pipeline_id = 1
                                        });
                                });

                            b1.Navigation("DeepSkyObjects");

                            b1.HasData(
                                new
                                {
                                    CameraPipelineConfigEntityId = 1,
                                    AnnotatePlanets = true,
                                    AutoStarCount = 30,
                                    AutoStarMagnitudeLimit = 3.0,
                                    DeepSkyLabelColor = "#F0E4FF",
                                    DeepSkyRingRadius = 12.0,
                                    LabelFontSize = 12.0,
                                    PlanetLabelColor = "#FFE8C5",
                                    PlanetRingRadius = 10.0,
                                    StarLabelColor = "#EBF5FF",
                                    StarRingRadius = 6.0,
                                    UseAutomaticStarSelection = true
                                });
                        });

                    b.OwnsOne("HVO.SkyMonitorV5.Data.Configurations.Entities.CircularApertureMaskSettings", "CircularApertureMask", b1 =>
                        {
                            b1.Property<int>("CameraPipelineConfigEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("MaskColor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("mask_color");

                            b1.Property<int>("MaskOpacity")
                                .HasColumnType("INTEGER")
                                .HasColumnName("mask_opacity");

                            b1.Property<int>("OffsetXPixels")
                                .HasColumnType("INTEGER")
                                .HasColumnName("mask_offset_x");

                            b1.Property<int>("OffsetYPixels")
                                .HasColumnType("INTEGER")
                                .HasColumnName("mask_offset_y");

                            b1.Property<int>("RadiusOffsetPixels")
                                .HasColumnType("INTEGER")
                                .HasColumnName("mask_radius_offset_px");

                            b1.HasKey("CameraPipelineConfigEntityId");

                            b1.ToTable("camera_pipeline_config");

                            b1.WithOwner()
                                .HasForeignKey("CameraPipelineConfigEntityId");

                            b1.HasData(
                                new
                                {
                                    CameraPipelineConfigEntityId = 1,
                                    MaskColor = "#000000",
                                    MaskOpacity = 220,
                                    OffsetXPixels = 0,
                                    OffsetYPixels = 0,
                                    RadiusOffsetPixels = -4
                                });
                        });

                    b.OwnsOne("HVO.SkyMonitorV5.Data.Configurations.Entities.ConstellationFigureOverlaySettings", "ConstellationFigures", b1 =>
                        {
                            b1.Property<int>("CameraPipelineConfigEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("LineColor")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("constellation_line_color");

                            b1.Property<double>("LineOpacity")
                                .HasColumnType("REAL")
                                .HasColumnName("constellation_line_opacity");

                            b1.Property<double>("LineThickness")
                                .HasColumnType("REAL")
                                .HasColumnName("constellation_line_thickness");

                            b1.Property<bool>("UseDashedLine")
                                .HasColumnType("INTEGER")
                                .HasColumnName("constellation_use_dashed_line");

                            b1.HasKey("CameraPipelineConfigEntityId");

                            b1.ToTable("camera_pipeline_config");

                            b1.WithOwner()
                                .HasForeignKey("CameraPipelineConfigEntityId");

                            b1.HasData(
                                new
                                {
                                    CameraPipelineConfigEntityId = 1,
                                    LineColor = "#7FB2FF",
                                    LineOpacity = 0.40000000000000002,
                                    LineThickness = 0.80000000000000004,
                                    UseDashedLine = true
                                });
                        });

                    b.OwnsOne("HVO.SkyMonitorV5.Data.Configurations.Entities.ImageEncodingSettings", "ProcessedImageEncoding", b1 =>
                        {
                            b1.Property<int>("CameraPipelineConfigEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Format")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("processed_image_format");

                            b1.Property<int>("Quality")
                                .HasColumnType("INTEGER")
                                .HasColumnName("processed_image_quality");

                            b1.HasKey("CameraPipelineConfigEntityId");

                            b1.ToTable("camera_pipeline_config");

                            b1.WithOwner()
                                .HasForeignKey("CameraPipelineConfigEntityId");

                            b1.HasData(
                                new
                                {
                                    CameraPipelineConfigEntityId = 1,
                                    Format = "Jpeg",
                                    Quality = 90
                                });
                        });

                    b.OwnsOne("HVO.SkyMonitorV5.Data.Configurations.Entities.RemoteDispatchSettings", "RemoteDispatch", b1 =>
                        {
                            b1.Property<int>("CameraPipelineConfigEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("dispatch_enabled");

                            b1.Property<string>("FanoutExchange")
                                .HasColumnType("TEXT")
                                .HasColumnName("dispatch_fanout_exchange");

                            b1.Property<string>("Mode")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("dispatch_mode");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("dispatch_region");

                            b1.Property<string>("S3Bucket")
                                .HasColumnType("TEXT")
                                .HasColumnName("dispatch_s3_bucket");

                            b1.HasKey("CameraPipelineConfigEntityId");

                            b1.ToTable("camera_pipeline_config");

                            b1.WithOwner()
                                .HasForeignKey("CameraPipelineConfigEntityId");

                            b1.HasData(
                                new
                                {
                                    CameraPipelineConfigEntityId = 1,
                                    Enabled = false,
                                    Mode = "None",
                                    Region = "us-west-2"
                                });
                        });

                    b.OwnsMany("HVO.SkyMonitorV5.Data.Configurations.Entities.CameraPipelineFilterEntity", "Filters", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("INTEGER")
                                .HasColumnName("display_order");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER")
                                .HasColumnName("enabled");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.Property<int>("pipeline_id")
                                .HasColumnType("INTEGER")
                                .HasColumnName("pipeline_id");

                            b1.HasKey("Id");

                            b1.HasIndex("pipeline_id");

                            b1.ToTable("camera_pipeline_filter", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("pipeline_id");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    DisplayOrder = 1,
                                    Enabled = true,
                                    Name = "CardinalDirections",
                                    pipeline_id = 1
                                },
                                new
                                {
                                    Id = 2,
                                    DisplayOrder = 2,
                                    Enabled = true,
                                    Name = "ConstellationFigures",
                                    pipeline_id = 1
                                },
                                new
                                {
                                    Id = 3,
                                    DisplayOrder = 3,
                                    Enabled = true,
                                    Name = "CelestialAnnotations",
                                    pipeline_id = 1
                                },
                                new
                                {
                                    Id = 4,
                                    DisplayOrder = 4,
                                    Enabled = false,
                                    Name = "OverlayText",
                                    pipeline_id = 1
                                },
                                new
                                {
                                    Id = 5,
                                    DisplayOrder = 5,
                                    Enabled = true,
                                    Name = "CircularApertureMask",
                                    pipeline_id = 1
                                });
                        });

                    b.Navigation("BackgroundStacker")
                        .IsRequired();

                    b.Navigation("CapturePacing")
                        .IsRequired();

                    b.Navigation("CardinalDirections")
                        .IsRequired();

                    b.Navigation("CelestialAnnotations")
                        .IsRequired();

                    b.Navigation("CircularApertureMask")
                        .IsRequired();

                    b.Navigation("ConstellationFigures")
                        .IsRequired();

                    b.Navigation("Filters");

                    b.Navigation("ProcessedImageEncoding")
                        .IsRequired();

                    b.Navigation("RemoteDispatch")
                        .IsRequired();
                });

            modelBuilder.Entity("HVO.SkyMonitorV5.Data.Configurations.Entities.RigCatalogEntryEntity", b =>
                {
                    b.HasOne("HVO.SkyMonitorV5.Data.Configurations.Entities.CameraCatalogCameraEntity", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HVO.SkyMonitorV5.Data.Configurations.Entities.CameraCatalogLensEntity", "Lens")
                        .WithMany()
                        .HasForeignKey("LensId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("Lens");
                });
#pragma warning restore 612, 618
        }
    }
}
