```yaml
version: '3.8'

services:
  hvo-playground:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__HualapaiValleyObservatory=Server=tcp:hvo.database.windows.net,1433;Initial Catalog=HualapaiValleyObservatory;Persist Security Info=False;User ID=roys;Password=1qaz!qaz;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    networks:
      - hvo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      - app-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hvo-playground.rule=Host(`localhost`)"
      - "traefik.http.routers.hvo-playground.entrypoints=web"
      - "traefik.http.services.hvo-playground.loadbalancer.server.port=8080"

networks:
  hvo-network:
    driver: bridge

volumes:
  app-data:
    driver: local
