name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const workflow_runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner,
              repo,
              per_page: 100,
              status: 'completed'
            });
            const runs = workflow_runs.data.workflow_runs;
            const runsToDelete = runs.slice(10); // keep only the latest 10
            for (const run of runsToDelete) {
              await github.rest.actions.deleteWorkflowRun({
                owner,
                repo,
                run_id: run.id
              });
              console.log(`Deleted run: ${run.id}`);
            }
